name: dart_angular_grpc_frontend
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  angular_bloc: ^6.0.1
  bloc: ^6.1.0
  grpc: ^2.8.0

  dart_starter_common:
    path: '../common'

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.9.0
  build_test: ^1.0.0
  build_web_compilers: ^2.10.0
  pedantic: ^1.9.2
  test: ^1.6.3
