name: dart_starter_common
description: Common files between services
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  grpc: ^2.8.0
  logger: ^0.9.4
  protobuf: ^1.1.0
  stack_trace: ^1.9.6

dev_dependencies:
  path: ^1.7.0
  pedantic: ^1.9.2
  protoc_plugin: ^19.2.0+1
